name: Deploy markdown.html
description: Compress markdown.html and deploy to target directory
author: 'PJ568'

inputs:
  target-dir:
    description: Relative path under $GITHUB_WORKSPACE to deploy the minimized HTML file
    default: ""
  file-name:
    description: Name of the minimized HTML file
    default: "index.html"
  use-minified:
    description: Whether to use minified HTML file
    default: "true"
  use-all-in-one:
    description: Whether to use all-in-one HTML file
    default: "false"

runs:
  using: "composite"
  steps:

    - name: Get version
      id: version-get
      run: |
        chmod +x ./scripts/get-version.bash
        VERSION=$(./scripts/get-version.bash)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        if [ "$VERSION" != "0" ]; then
          echo "Version detected: $VERSION"
        else
          echo "No version detacted"
        fi
      shell: bash

    - name: Generate file name
      run: |
        USE_ALL_IN_ONE=""
        USE_MINIFIED=""
        if [ "${{ inputs.use-all-in-one }}" = "true" ]; then
          USE_ALL_IN_ONE=".allinone"
        fi
        if [ "${{ inputs.use-minified }}" = "true" ]; then
          USE_MINIFIED=".min"
        fi
        echo "file_name=index${USE_ALL_IN_ONE}${USE_MINIFIED}.html" >> $GITHUB_OUTPUT
      shell: bash

    - name: Deploy pre-generated markdown.html file
      uses: robinraju/release-downloader@v1
      with:
        repository: 'PJ-568/MAKRDOWN.HTML'
        tag: ${{ steps.version-get.outputs.version }}
        fileName: ${{ steps.file-name.outputs.file_name }}
        tarBall: false
        zipBall: false
        out-file-path: ${{ inputs.target-dir }}

    - name: Rename file
      run: |
        mv $GITHUB_WORKSPACE/${{ steps.file-name.outputs.file_name }} $GITHUB_WORKSPACE/${{ inputs.file-name }}
      shell: bash

branding:
  icon: 'book-open'
  color: 'green'