[package]
name = "markdown-html-generator"
version = "1.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minify-html = "0.15.0"
reqwest = { version = "0.12.20", features = ["blocking"] }
scraper = "0.23.1"
